version: '3'
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=production 
      - DB_URI=mongodb://srv-captain--make-chat-2/mydatabase?authSource=admin
    env_file:
      - .env 
    ports:
      - '3001:3000'
    depends_on:
      - database

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: captain42
      DB_URI: mongodb://srv-captain--make-chat-2/mydatabase?authSource=admin
    ports:
      - '27017:27017'

