version: '3'
services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=production 
    env_file:
      - .env 
    ports:
      - '3000:3000'
    depends_on:
      - database

  database:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: captain42
    ports:
      - '27017:27017'

